/**
 * IMPR AI Conference Hub data dictionary.
 * Keep this file free of personal contact fields. Private registration data must
 * live in a separate, access-restricted spreadsheet outside this application.
 */
var COMMON_FIELDS = [
  {
    name: "created_at",
    type: "datetime",
    required: true,
    unique: false,
    public: true,
  },
  {
    name: "updated_at",
    type: "datetime",
    required: true,
    unique: false,
    public: true,
  },
  {
    name: "status",
    type: "string",
    required: true,
    unique: false,
    public: true,
  },
  {
    name: "is_public",
    type: "boolean",
    required: true,
    unique: false,
    public: true,
  },
];

var SHEET_SCHEMAS = {
  Settings: {
    publicApi: true,
    idField: "setting_id",
    fields: [
      {
        name: "setting_id",
        type: "uuid",
        required: true,
        unique: true,
        public: true,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "setting_key",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "value_zh",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "value_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "data_type",
        type: "enum",
        required: true,
        unique: false,
        public: true,
      },
    ].concat(COMMON_FIELDS),
    example: [
      "SET-DEMO-001",
      "IMPR-DEMO",
      "event_name",
      "IMPR AI 國際論壇",
      "IMPR AI Forum",
      "string",
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "published",
      true,
    ],
  },
  Agenda: {
    publicApi: true,
    idField: "agenda_id",
    fields: [
      {
        name: "agenda_id",
        type: "uuid",
        required: true,
        unique: true,
        public: true,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "session_date",
        type: "date",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "start_time",
        type: "time",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "end_time",
        type: "time",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "room",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "title_zh",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "title_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "description_zh",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "description_en",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "speaker_ids",
        type: "string[]",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "sort_order",
        type: "integer",
        required: true,
        unique: false,
        public: true,
      },
    ].concat(COMMON_FIELDS),
    example: [
      "AGN-DEMO-001",
      "IMPR-DEMO",
      "2026-10-01",
      "09:00",
      "09:30",
      "主會場",
      "開幕致詞",
      "Opening Remarks",
      "",
      "",
      "SPK-DEMO-001",
      10,
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "published",
      true,
    ],
  },
  Speakers: {
    publicApi: true,
    idField: "speaker_id",
    fields: [
      {
        name: "speaker_id",
        type: "uuid",
        required: true,
        unique: true,
        public: true,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "name_zh",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "name_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "title_zh",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "title_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "organization_zh",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "organization_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "bio_zh",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "bio_en",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "photo_url",
        type: "url",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "website_url",
        type: "url",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "sort_order",
        type: "integer",
        required: true,
        unique: false,
        public: true,
      },
    ].concat(COMMON_FIELDS),
    example: [
      "SPK-DEMO-001",
      "IMPR-DEMO",
      "範例講者",
      "Example Speaker",
      "執行長",
      "Chief Executive Officer",
      "範例機構",
      "Example Organisation",
      "經主辦單位確認的公開簡介。",
      "Public biography approved by the organiser.",
      "https://example.com/speaker.jpg",
      "https://example.com",
      10,
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "published",
      true,
    ],
  },
  FAQ: {
    publicApi: true,
    idField: "faq_id",
    fields: [
      {
        name: "faq_id",
        type: "uuid",
        required: true,
        unique: true,
        public: true,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "category",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "question_zh",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "answer_zh",
        type: "text",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "question_en",
        type: "string",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "answer_en",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "sort_order",
        type: "integer",
        required: true,
        unique: false,
        public: true,
      },
    ].concat(COMMON_FIELDS),
    example: [
      "FAQ-DEMO-001",
      "IMPR-DEMO",
      "general",
      "活動資訊何時公布？",
      "請以主辦單位核准後公布的資訊為準。",
      "When will event details be announced?",
      "Please refer to information approved and published by the organiser.",
      10,
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "published",
      true,
    ],
  },
  Glossary: {
    publicApi: true,
    idField: "glossary_id",
    fields: [
      {
        name: "glossary_id",
        type: "uuid",
        required: true,
        unique: true,
        public: true,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "term_zh",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "term_en",
        type: "string",
        required: true,
        unique: false,
        public: true,
      },
      {
        name: "definition_zh",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "definition_en",
        type: "text",
        required: false,
        unique: false,
        public: true,
      },
      {
        name: "sort_order",
        type: "integer",
        required: true,
        unique: false,
        public: true,
      },
    ].concat(COMMON_FIELDS),
    example: [
      "GLO-DEMO-001",
      "IMPR-DEMO",
      "企業風險管理",
      "Enterprise Risk Management",
      "組織辨識、評估及管理風險的整合方法。",
      "An integrated approach to identifying, assessing, and managing organisational risk.",
      10,
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "published",
      true,
    ],
  },
  Questions: {
    publicApi: false,
    idField: "question_id",
    fields: [
      {
        name: "question_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "session_id",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "question_text",
        type: "text",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "language",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "moderation_status",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "submitted_at",
        type: "datetime",
        required: true,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "QUE-DEMO-001",
      "IMPR-DEMO",
      "AGN-DEMO-001",
      "請問這項政策的執行時程為何？",
      "zh-Hant",
      "pending",
      "2026-10-01T10:00:00+08:00",
      "2026-10-01T10:00:00+08:00",
      "2026-10-01T10:00:00+08:00",
      "pending",
      false,
    ],
  },
  RegistrationStats: {
    publicApi: false,
    idField: "stat_id",
    fields: [
      {
        name: "stat_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "stat_date",
        type: "date",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "category",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "registered_count",
        type: "integer",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "attended_count",
        type: "integer",
        required: false,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "STA-DEMO-001",
      "IMPR-DEMO",
      "2026-09-01",
      "all",
      120,
      0,
      "2026-09-01T18:00:00+08:00",
      "2026-09-01T18:00:00+08:00",
      "active",
      false,
    ],
  },
  SpeakerTracking: {
    publicApi: false,
    idField: "tracking_id",
    fields: [
      {
        name: "tracking_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "speaker_id",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "contact_owner",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "contact_status",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "last_contacted_at",
        type: "datetime",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "next_action_at",
        type: "datetime",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "internal_notes",
        type: "text",
        required: false,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "TRK-DEMO-001",
      "IMPR-DEMO",
      "SPK-DEMO-001",
      "議程組",
      "invited",
      "2026-08-20T10:00:00+08:00",
      "2026-08-27T10:00:00+08:00",
      "不記錄電話或電子郵件。",
      "2026-08-20T10:00:00+08:00",
      "2026-08-20T10:00:00+08:00",
      "active",
      false,
    ],
  },
  Tasks: {
    publicApi: false,
    idField: "task_id",
    fields: [
      {
        name: "task_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "title",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "description",
        type: "text",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "owner_role",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "due_date",
        type: "date",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "priority",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "task_status",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "TSK-DEMO-001",
      "IMPR-DEMO",
      "確認雙語議程",
      "由議程負責人完成最終人工確認。",
      "議程組",
      "2026-09-15",
      "high",
      "todo",
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "active",
      false,
    ],
  },
  AIOutputs: {
    publicApi: false,
    idField: "ai_output_id",
    fields: [
      {
        name: "ai_output_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "source_type",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "source_id",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "task_type",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "model_key",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "prompt_version",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "output_text",
        type: "text",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "is_draft",
        type: "boolean",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "review_status",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "reviewed_by",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "reviewed_at",
        type: "datetime",
        required: false,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "AIO-DEMO-001",
      "IMPR-DEMO",
      "faq",
      "FAQ-DEMO-001",
      "translation",
      "OPENAI_TRANSLATION_MODEL",
      "v1",
      "【AI 初稿】待人工審核的內容。",
      true,
      "pending",
      "",
      "",
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "draft",
      false,
    ],
  },
  AuditLog: {
    publicApi: false,
    idField: "audit_id",
    fields: [
      {
        name: "audit_id",
        type: "uuid",
        required: true,
        unique: true,
        public: false,
      },
      {
        name: "event_code",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "request_id",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "actor_type",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "actor_hash",
        type: "string",
        required: false,
        unique: false,
        public: false,
      },
      {
        name: "action",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "resource",
        type: "string",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "result",
        type: "enum",
        required: true,
        unique: false,
        public: false,
      },
      {
        name: "details_json",
        type: "json",
        required: false,
        unique: false,
        public: false,
      },
    ].concat(
      COMMON_FIELDS.map(function (field) {
        return Object.assign({}, field, { public: false });
      }),
    ),
    example: [
      "AUD-DEMO-001",
      "IMPR-DEMO",
      "REQ-DEMO-001",
      "anonymous",
      "sha256:example",
      "question.create",
      "Questions",
      "success",
      '{"mode":"test"}',
      "2026-08-22T09:00:00+08:00",
      "2026-08-22T09:00:00+08:00",
      "recorded",
      false,
    ],
  },
};

function getSheetSchema(sheetName) {
  var schema = SHEET_SCHEMAS[sheetName];
  if (!schema) throw new Error("Unknown sheet schema: " + sheetName);
  return schema;
}

function getPublicFieldNames(sheetName) {
  return getSheetSchema(sheetName)
    .fields.filter(function (field) {
      return field.public;
    })
    .map(function (field) {
      return field.name;
    });
}
